name: 1. Auto Open PR

on:
  push:
    branches:
      - hml

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        # Tenta criar o PR. Se já existir um aberto, ele avisa e não falha o pipeline.
        run: |
          gh pr create \
            --base main \
            --head hml \
            --title "Deploy HML to Main: ${{ github.sha }}" \
            --body "PR automático criado após push na branch hml. Aguardando aprovação para deploy." \
          || echo "PR já existe ou não há mudanças."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}